export {HeadedButton} from '@/components/Button/headed-button';
export {HeadedAccordion} from '@/components/Accordion/headed-accordion';
export {HeadedCard} from '@/components/Card/headed-card';
export {HeadedDialog} from '@/components/Dialog/headed-dialog';
export {HeadedDropdown} from '@/components/Dropdown/headed-dropdown';
export {HeadedLink} from '@/components/Link/headed-link';
export {HeadedModal} from '@/components/Modal/headed-modal';
export {HeadedPopover} from '@/components/Popover/headed-popover';
export {HeadedSelect} from '@/components/Select/headed-select';
// export { HeadedSwitch } from '@/components/Switch/primary-switch';
export {HeadedTabs} from '@/components/Tabs/headed-tabs';